// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ODataWebApiIssue1979Repro01.DataSources;

namespace ODataWebApiIssue1979Repro01.Migrations
{
    [DbContext(typeof(PetsDbContext))]
    [Migration("20200124132855_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ODataWebApiIssue1979Repro01.Models.Person", b =>
                {
                    b.Property<int>("ShadowId")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("ShadowId", "Id");

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("ODataWebApiIssue1979Repro01.Models.Pet", b =>
                {
                    b.Property<int>("ShadowId")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<int?>("OwnerId")
                        .HasColumnType("int");

                    b.HasKey("ShadowId", "Id");

                    b.HasIndex("ShadowId", "OwnerId")
                        .IsUnique()
                        .HasFilter("[OwnerId] IS NOT NULL");

                    b.ToTable("Pets");
                });

            modelBuilder.Entity("ODataWebApiIssue1979Repro01.Models.Pet", b =>
                {
                    b.HasOne("ODataWebApiIssue1979Repro01.Models.Person", "Owner")
                        .WithOne()
                        .HasForeignKey("ODataWebApiIssue1979Repro01.Models.Pet", "ShadowId", "OwnerId");
                });
#pragma warning restore 612, 618
        }
    }
}
